---An entity that is not valid, but still has all the functions, IsValid() will return false
---@class InvalidEntity : Entity
NULL = NULL

---@alias SteamID64 string A 64-bit Steam ID, also known as SteamID64
---@alias SteamID string A Steam ID, also known as SteamID

---@alias NSCOP.HookEventName
---| "AcceptInput"
---| "AddDeathNotice"
---| "AdjustMouseSensitivity"
---| "AllowPlayerPickup"
---| "CalcMainActivity"
---| "KeyPress"
---| "KeyRelease"
---| "PlayerButtonDown"
---| "PlayerButtonUp"
---| "PlayerCanHearPlayersVoice"
---| "PlayerCanSeePlayersChat"
---| "PlayerDeath"
---| "PlayerDeathSound"
---| "PlayerDisconnected"
---| "PlayerFootstep"
---| "PlayerHurt"
---| "PlayerInitialSpawn"
---| "PlayerSay"
---| "PlayerSpawn"

---The base element of the HUD. Used to determine which HUD element to block with HUDShouldDraw
---<br>Elements list: https://wiki.facepunch.com/gmod/HUD_Element_List
---@alias NSCOP.HUDBaseElement
---| "CHudAmmo"
---| "CHudBattery"
---| "CHudChat"
---| "CHudCrosshair"
---| "CHudCloseCaption"
---| "CHudDamageIndicator"
---| "CHudHistoryResource"
---| "CHudDeathNotice"
---| "CHudGeiger"
---| "CHudGMod"
---| "CHudHealth"
---| "CHudHintDisplay"
---| "CHudMenu"
---| "CHudMessage"
---| "CHudPoisonDamageIndicator"
---| "CHudSecondaryAmmo"
---| "CHudSquadStatus"
---| "CHudTrain"
---| "CHudVehicle"
---| "CHudWeapon"
---| "CHudWeaponSelection"
---| "CHudZoom"
---| "NetGraph"
---| "CHUDQuickInfo" The sudden change in the prefix CHUD is not a mistake
---| "CHudSuitPower"
